// src/app/layout.tsx
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js 15 + Tailwind v4",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        {children}
        <ThemeToggle />
      </body>
    </html>
  );
}
